# Generated by Django 2.2.3 on 2019-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20190715_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
