# Generated by Django 2.2.3 on 2019-07-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instituicao',
            field=models.CharField(default='vida', max_length=30),
            preserve_default=False,
        ),
    ]
