# Generated by Django 2.2.3 on 2019-07-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20190715_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
