# Generated by Django 2.2.3 on 2019-07-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20190719_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/profile/default.jpeg', null=True, upload_to='fotos/profile'),
        ),
    ]
