# Generated by Django 2.2.3 on 2019-07-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20190719_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/profile/default.jpeg', null=True, upload_to='fotos/profile/teste.jpg'),
        ),
    ]
