# Generated by Django 2.2.3 on 2019-07-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20190723_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/profile/default.jpeg', null=True, upload_to='fotos/profile/'),
        ),
    ]
