# Generated by Django 2.2.3 on 2019-07-23 22:18

from django.db import migrations, models
import portal_ensino.usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20190723_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/profile/default.jpeg', null=True, upload_to=portal_ensino.usuarios.models.renomear_imagem),
        ),
    ]
