# Generated by Django 2.2.3 on 2019-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20190723_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(default='AAAA-MM-DD'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instituicao',
            field=models.CharField(default='UNIPAC', max_length=30),
        ),
    ]
