# Generated by Django 2.2.3 on 2019-11-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20191119_1133'),
        ('usuarios', '0016_auto_20191124_1056'),
    ]

    operations = [
    ]
