# Generated by Django 2.2.3 on 2019-12-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20191216_2207'),
        ('usuarios', '0017_merge_20191124_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aula_atual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aulas.Aulas'),
        ),
    ]
