# Generated by Django 3.2 on 2021-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0002_user_aula_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to. A user will get all permissions granted to each of their '
                          'groups.',
                related_name='user_set', related_query_name='user', to='auth.Group',
                verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this user should be treated as active. Unselect this instead of '
                          'deleting accounts.',
                verbose_name='active'),
        ),
    ]
