# Generated by Django 2.2.3 on 2019-12-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aulas',
            options={'verbose_name_plural': 'Aulas'},
        ),
    ]
