# Generated by Django 2.2.3 on 2019-12-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20191216_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='aulas/materiais'),
        ),
    ]
