# Generated by Django 2.2.3 on 2019-12-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_aulas_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.TextField()),
                ('alt1', models.TextField()),
                ('alt2', models.TextField()),
                ('alt3', models.TextField()),
                ('alt4', models.TextField()),
                ('resposta_correta', models.TextField()),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
    ]
