# Generated by Django 2.2.3 on 2019-12-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_questoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questoes',
            options={'verbose_name': 'Qugitestão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='questoes',
            name='aula_referente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aulas.Aulas'),
        ),
    ]
