# Generated by Django 2.2.8 on 2020-04-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_auto_20191226_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questoes',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
