# Generated by Django 3.2 on 2021-04-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='resposta_correta',
            field=models.TextField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')]),
        ),
    ]
