# Generated by Django 3.2 on 2021-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0002_alter_questoes_resposta_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoes',
            name='resposta_correta',
            field=models.TextField(choices=[('a', 'a'), ('a', 'b'), ('a', 'c'), ('a', 'd')]),
        ),
    ]
